In [ ]:
import numpy as np

In [ ]:
vector = [1, 2, 3]

In [ ]:
print(type(vector))

<class 'list'>


In [ ]:
npvector = np.array(vector)

In [ ]:
print(type(npvector))

<class 'numpy.ndarray'>


In [ ]:
npvector.shape

(3,)

In [ ]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 1, 1]
]

In [ ]:
npmatrix = np.array(matrix)

In [ ]:
npmatrix.shape

(4, 3)

In [ ]:
matrix2 = [
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1, 1]
]

In [ ]:
npmatrix2 = np.array(matrix2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
s = 3 # SCALAR
rv = [1, 2, 3] # ROW_VECTOR
cv = [[1],[2],[3]] # COLUMN_VECTOR
m = [
    [1,1,1],
    [1,1,1],
    [1,1,1]
]  # MATRIX
t = [
    [[1,2,3],[4,5,6,],[7,8,9]],
    [[1,1,1],[2,2,2],[3,3,3]],
    [[0,0,0],[0,0,0],[0,0,0]]
] # TENSOR


In [ ]:
narr = np.array([1,2,3])
narr

array([1, 2, 3])

In [ ]:
np.resize(narr,(2,4))

array([[1, 2, 3, 0],
       [0, 0, 0, 0]])

In [ ]:
narr.resize((3,3), refcheck=False)

In [ ]:
matrix_ones = np.ones((5,4))
matrix_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
matrix_zeros = np.zeros((4,5))
matrix_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
narr.diagonal()

array([1, 0, 0])

In [ ]:
np.diag(narr)

array([1, 0, 0])

In [ ]:
np.repeat([4,3,2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [ ]:
m1 = np.ones((3,3), int)
m1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
m2 = np.zeros((3,3), int)
m2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.vstack([m1,m2]) #row stacking

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.hstack([m1,m2]) #column stacking

array([[1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0]])

In [ ]:
 [1,2,3] * [4,5,6]

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
 a = np.array([1,2,3])
 b = np.array([4,5,6])
 c = a * b
 c

array([ 4, 10, 18])

In [ ]:
a ** 2

array([1, 4, 9])

In [ ]:
a ** 3

array([ 1,  8, 27])

In [ ]:
a ** 1/3

array([0.33333333, 0.66666667, 1.        ])

In [ ]:
a = np.array([1,2,3])

In [ ]:
p = a.dot(b) # ضرب داخلی , Inner Product ,  Dot Product
print(p)

32


In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.dot(A, B)
print(C)


[[19 22]
 [43 50]]


In [ ]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [ ]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
print(narr.sum())

6


In [ ]:
print(narr.max())

3


In [ ]:
print(narr.min())

0


In [ ]:
print(narr.argmax())  # index of max value

2


In [ ]:
print(narr.argmin())  # index of min value

3


In [ ]:
print(narr.mean())  # میانگین

0.6666666666666666


In [ ]:
print(narr.std()) # انحراف استاندارد

1.0540925533894598


In [ ]:
mr = np.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [ ]:
print(mr[2])   #[start : end (Not Included) : step]

4


In [ ]:
print(mr[2:8])

[ 4  9 16 25 36 49]


In [ ]:
print(mr[1:5])

[ 1  4  9 16]


In [ ]:
print(mr[1:-3])

[  1   4   9  16  25  36  49  64  81 100 121]


In [ ]:
print(mr[2:])

[  4   9  16  25  36  49  64  81 100 121 144 169 196]


In [ ]:
print(mr[:4])

[0 1 4 9]


In [ ]:
print(mr[-2:])

[169 196]


In [ ]:
print(mr[-3:-1])

[144 169]


In [ ]:
print(mr[-2:])

[169 196]


In [ ]:
print(mr[5:12:3])

[ 25  64 121]


In [ ]:
import numpy as np
import sys

In [ ]:
%%time
tarr = np.random.randint(0,10,(10000000, ))
