In [6]:
import numpy as np

In [4]:
vector = [1, 2, 3]

In [5]:
print(type(vector))

<class 'list'>


In [7]:
npvector = np.array(vector)

In [8]:
print(type(npvector))

<class 'numpy.ndarray'>


In [9]:
npvector.shape

(3,)

In [25]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 1, 1]
]

In [26]:
npmatrix = np.array(matrix)

In [27]:
npmatrix.shape

(4, 3)

In [14]:
matrix2 = [
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1, 1]
]

In [15]:
npmatrix2 = np.array(matrix2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [17]:
s = 3 # SCALAR
rv = [1, 2, 3] # ROW_VECTOR
cv = [[1],[2],[3]] # COLUMN_VECTOR
m = [
    [1,1,1],
    [1,1,1],
    [1,1,1]
]  # MATRIX
t = [
    [[1,2,3],[4,5,6,],[7,8,9]],
    [[1,1,1],[2,2,2],[3,3,3]],
    [[0,0,0],[0,0,0],[0,0,0]]
] # TENSOR


In [19]:
narr = np.array([1,2,3])
narr

array([1, 2, 3])

In [24]:
np.resize(narr,(2,4))

array([[1, 2, 3, 0],
       [0, 0, 0, 0]])

In [21]:
narr.resize((3,3), refcheck=False)

In [23]:
matrix_ones = np.ones((5,4))
matrix_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
matrix_zeros = np.zeros((4,5))
matrix_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
narr.diagonal()

array([1, 0, 0])

In [36]:
np.diag(narr)

array([1, 0, 0])

In [34]:
np.repeat([4,3,2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [37]:
m1 = np.ones((3,3), int)
m1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
m2 = np.zeros((3,3), int)
m2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
np.vstack([m1,m2]) #row stacking

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
np.hstack([m1,m2]) #column stacking

array([[1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0]])

In [41]:
 [1,2,3] * [4,5,6]

TypeError: can't multiply sequence by non-int of type 'list'

In [44]:
 a = np.array([1,2,3])
 b = np.array([4,5,6])
 c = a * b
 c

array([ 4, 10, 18])

In [45]:
a ** 2

array([1, 4, 9])

In [46]:
a ** 3

array([ 1,  8, 27])

In [48]:
a ** 1/3

array([0.33333333, 0.66666667, 1.        ])

In [50]:
a = np.array([1,2,3])

In [53]:
p = a.dot(b) # ضرب داخلی , Inner Product ,  Dot Product
print(p)

32


In [54]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.dot(A, B)
print(C)


[[19 22]
 [43 50]]


In [55]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [58]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
`