In [6]:
import numpy as np

In [4]:
vector = [1, 2, 3]

In [5]:
print(type(vector))

<class 'list'>


In [7]:
npvector = np.array(vector)

In [8]:
print(type(npvector))

<class 'numpy.ndarray'>


In [9]:
npvector.shape

(3,)

In [25]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 1, 1]
]

In [26]:
npmatrix = np.array(matrix)

In [27]:
npmatrix.shape

(4, 3)

In [14]:
matrix2 = [
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1, 1]
]

In [15]:
npmatrix2 = np.array(matrix2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [17]:
s = 3 # SCALAR
rv = [1, 2, 3] # ROW_VECTOR
cv = [[1],[2],[3]] # COLUMN_VECTOR
m = [
    [1,1,1],
    [1,1,1],
    [1,1,1]
]  # MATRIX
t = [
    [[1,2,3],[4,5,6,],[7,8,9]],
    [[1,1,1],[2,2,2],[3,3,3]],
    [[0,0,0],[0,0,0],[0,0,0]]
] # TENSOR


In [19]:
narr = np.array([1,2,3])
narr

array([1, 2, 3])

In [24]:
np.resize(narr,(2,4))

array([[1, 2, 3, 0],
       [0, 0, 0, 0]])

In [21]:
narr.resize((3,3), refcheck=False)

In [23]:
matrix_ones = np.ones((5,4))
matrix_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
matrix_zeros = np.zeros((4,5))
matrix_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])