In [1]:
import pandas as pd

In [6]:
print(pd.__version__)

2.2.2


In [8]:
a = pd.Series([2,3,4,5] , index=['a','b','c','d'])

In [12]:
type(a.values)

numpy.ndarray

In [14]:
type(a)

pandas.core.series.Series

In [18]:
a.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [20]:
a.values

array([2, 3, 4, 5], dtype=int64)

In [22]:
a['a']

2

In [26]:
a['a':'c']

a    2
b    3
c    4
dtype: int64

In [39]:
grades_dict = {'A':4 ,"A-":3.5 , "B":3 , "B-":2.5 ,"C":2}
grades = pd.Series(grades_dict)

In [30]:
grades.values

array([4. , 3.5, 3. , 2.5, 2. ])

In [32]:
grades.index

Index(['A', 'A-', 'B', 'B-', 'C'], dtype='object')

In [34]:
grades[1:3]

A-    3.5
B     3.0
dtype: float64

In [41]:
marks= pd.Series([85,80,75,70,65] ,index=['A','A-','B','B-','C'])

In [43]:
rs = pd.DataFrame({'grades':grades , 'marks':marks})

In [54]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [56]:
rs.T

A    A-     B    B-     C
grades   4.0   3.5   3.0   2.5   2.0
marks   85.0  80.0  75.0  70.0  65.0

In [64]:
rs.values

array([[ 4. , 85. ],
       [ 3.5, 80. ],
       [ 3. , 75. ],
       [ 2.5, 70. ],
       [ 2. , 65. ]])

In [66]:
rs.values[2,0]

3.0

In [72]:
rs.columns

Index(['grades', 'marks'], dtype='object')

In [78]:
rs['scale'] = 100*(rs['marks']/90)

In [80]:
rs

grades  marks      scale
A      4.0     85  94.444444
A-     3.5     80  88.888889
B      3.0     75  83.333333
B-     2.5     70  77.777778
C      2.0     65  72.222222

In [82]:
del rs['scale']

In [84]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [86]:
g = rs[rs['marks']>70]

In [88]:
g

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75

In [11]:
A = pd.DataFrame([{'a':1 , 'b':2},{'b':3 , 'c':4}])

In [13]:
A

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [17]:
A.fillna(0)

a  b    c
0  1.0  2  0.0
1  0.0  3  4.0

In [21]:
A.dropna?

Signature:
A.dropna(
    *,
    axis: 'Axis' = 0,
    how: 'AnyAll | lib.NoDefault' = <no_default>,
    thresh: 'int | lib.NoDefault' = <no_default>,
    subset: 'IndexLabel | None' = None,
    inplace: 'bool' = False,
    ignore_index: 'bool' = False,
) -> 'DataFrame | None'
Docstring:
Remove missing values.

See the :ref:`User Guide <missing_data>` for more on which values are
considered missing, and how to work with missing data.

Parameters
----------
axis : {0 or 'index', 1 or 'columns'}, default 0
    Determine if rows or columns which contain missing values are
    removed.

    * 0, or 'index' : Drop rows which contain missing values.
    * 1, or 'columns' : Drop columns which contain missing value.

    Only a single axis is allowed.

how : {'any', 'all'}, default 'any'
    Determine if row or column is removed from DataFrame, when we have
    at least one NA or all NA.

    * 'any' : If any NA values are present, drop that row or column.
    * 'all' : If all values are NA, dr

In [23]:
A = pd.Series(['a' ,'b','c'], index=[1,3,5])

In [25]:
A[1]

'a'

In [27]:
A[1:3]

3    b
5    c
dtype: object

In [29]:
A.loc[1:3]

1    a
3    b
dtype: object

In [31]:
A.iloc[1:3]

3    b
5    c
dtype: object

In [47]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [49]:
rs.iloc[2,:]

grades     3.0
marks     75.0
Name: B, dtype: float64

In [51]:
rs.iloc[::-1,:]

grades  marks
C      2.0     65
B-     2.5     70
B      3.0     75
A-     3.5     80
A      4.0     85