# NumPy

### numpy list is much faster that python list

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5],dtype='i')
b = np.array((1,6,3,4,9),dtype='f')
print(a)
print(b)

[1 2 3 4 5]
[1. 6. 3. 4. 9.]


In [ ]:
type(a)
type(b)

numpy.ndarray

In [ ]:
a.dtype

dtype('int32')

In [ ]:
b.dtype

dtype('float32')

----------------------------------------
### Demensions

In [ ]:
c = np.array([[1,2,3] , [4,5,6]])
print(c.ndim)

2


In [ ]:
d = np.array([[[1,2,3] ,[4,5,6]],[[1,2,3],[4,5,6]]])
print(d)
print(d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
print(d.shape[0] , d.shape[1] , d.shape[2])
print(d[1,0,2])

2 2 3
3


In [ ]:
print(d[0][1][0])

4


In [ ]:
print(d[0,1,0])

4


In [ ]:
c= np.array([[1,2],[1,2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
c = np.array([[[1,2,3],[4,5,6],[0,0,-1]], [[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

In [ ]:
c.ndim

3

In [ ]:
type(c)

numpy.ndarray

----------------------------------------
### shape  

#### $*$ The shape of an array is the number of elements in each dimension.

In [ ]:
help(np.shape)

Help on _ArrayFunctionDispatcher in module numpy:

shape(a)
    Return the shape of an array.

    Parameters
    ----------
    a : array_like
        Input array.

    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.

    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.

    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()

    >>> a = np.array([(1, 2), (3, 4), (5, 6)],
    ...              dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (3,)
    >>> a.shape
    (3,)



In [ ]:
c.shape

(2, 3, 3)

In [ ]:
c.shape[1]

3

In [ ]:
c.ndim

3

In [ ]:
e = np.array([[[[1,2,3],[1,2,3]]]])
print(e.shape)
print(e.ndim)

(1, 1, 2, 3)
4


In [ ]:
f = np.array([2])
f.ndim

1

In [ ]:
g = np.array(3)

In [ ]:
g.ndim

0

----------------------------------------
### size

#### $*$ Gives the total number of elements .

In [ ]:
print(g.size)
print(f.size)
print(e.size)
print(d.size)
print(c.size)
print(b.size)
print(a.size)

1
1
6
12
18
5
5


----------------------------------------
### nbytes



#### $*$The number of bytes that it takes in memory

In [ ]:
print(g.nbytes)
print(f.nbytes)
print(e.nbytes)
print(d.nbytes)
print(c.nbytes)
print(b.nbytes)
print(a.nbytes)

4
4
24
48
72
20
20


### arange

#### arange(start, stop, step,, dtype) : Returns an array with evenly spaced elements as per the interval.

In [ ]:
a = np.arange(100)

In [ ]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
a = np.arange(20,100,4,'float32')

In [ ]:
print(a)

[20. 24. 28. 32. 36. 40. 44. 48. 52. 56. 60. 64. 68. 72. 76. 80. 84. 88.
 92. 96.]


### random

In [ ]:
from numpy import random
x = random.randint(100)
print(x)

91


In [ ]:
x = random.randint(100, size=(5))
print(x)

[66 92 75 45 44]


In [ ]:
x = random.randint(100, size=(3, 5))
print(x)

[[12 99 70 48  4]
 [53 64 22 24 50]
 [30 62 36 46 11]]


In [ ]:
x = random.rand(10)
print(x)

[0.54978589 0.30809422 0.90717483 0.43686087 0.04850644 0.13160317
 0.64484335 0.28514687 0.53248315 0.50859871]


In [ ]:
x = random.rand(3, 5)
print(x)

[[0.60545603 0.13934186 0.48933363 0.7203497  0.1732698 ]
 [0.67059157 0.43349478 0.46797112 0.82435309 0.2523013 ]
 [0.29625651 0.21425571 0.9607617  0.30893662 0.82758895]]


In [ ]:
x = random.choice([3, 5, 7, 9])
print(x)

3


In [ ]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[7 5 3 7 5]
 [7 7 9 5 9]
 [7 7 7 7 5]]


In [ ]:
B = random.randn(10)
print(B)

[-0.97888345 -0.79536492 -0.67426448  0.81977847  0.51197223 -1.02094928
 -0.06235829 -0.41682735 -1.01111964  1.05155149]


In [ ]:
C  = random.rand(2,3,4,2)
print(C)

[[[[0.69991983 0.44297422]
   [0.68137032 0.16075331]
   [0.81763751 0.4353439 ]
   [0.30843444 0.63491917]]

  [[0.98236918 0.97956565]
   [0.38781851 0.41128512]
   [0.98800561 0.5685431 ]
   [0.0256113  0.19179184]]

  [[0.37856993 0.09644467]
   [0.93561366 0.87012338]
   [0.03263357 0.74651193]
   [0.57748844 0.35463929]]]


 [[[0.24477976 0.10164465]
   [0.05064284 0.10545007]
   [0.52069016 0.23627739]
   [0.54072417 0.62901753]]

  [[0.79742042 0.59390395]
   [0.93077873 0.39404464]
   [0.35461336 0.1367498 ]
   [0.15993369 0.15032652]]

  [[0.07328601 0.08239671]
   [0.19595304 0.89916789]
   [0.7286973  0.62283415]
   [0.37536003 0.33834137]]]]


### Permutations

#### A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

In [ ]:
A = random.permutation(np.arange(10))
print(A)

[8 5 0 6 7 2 3 1 9 4]


###  reshape


#### Reshaping means changing the shape of an array.

#### The shape of an array is the number of elements in each dimension.


#### By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
D = np.arange(100).reshape(4, 25)
print(D)
print(D.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]
(4, 25)


In [ ]:
D = np.arange(100).reshape(4, 5,5)
print(D)
print(D.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]
(4, 5, 5)


### Slicing

In [ ]:
import numpy as np
a = np.arange(100)
b = a[3:10]

In [ ]:
b

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
b[0] = -1200
b

array([-1200,     4,     5,     6,     7,     8,     9])

In [ ]:
a

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [ ]:
b = a[5:21].copy()
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
a[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
a[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [ ]:
a ==-1200

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
b = (a==-1200)*np.arange(a.size)
b

array([0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
idx = np.argwhere(a==-1200)[0][0]

In [ ]:
idx

3

In [ ]:
a[idx] = 3
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a = np.round(10*np.random.rand(5,4))
a

array([[6., 1., 8., 9.],
       [2., 7., 2., 5.],
       [7., 6., 1., 9.],
       [1., 5., 5., 6.],
       [1., 4., 8., 5.]])

In [ ]:
a[1,2]

7.0

In [ ]:
a[1,:]

array([ 8.,  8.,  7., 10.])

In [ ]:
a[:,2]

array([9., 7., 5., 9., 5.])

In [ ]:
a[1:3,2:4]

array([[ 7., 10.],
       [ 5.,  0.]])

#### The transpose of a matrix is obtained by moving the rows data to the column and columns data to the rows .

In [ ]:
a.T

array([[ 4.,  8.,  9.,  9.,  1.],
       [ 5.,  8.,  5.,  1.,  4.],
       [ 9.,  7.,  5.,  9.,  5.],
       [ 5., 10.,  0.,  5.,  9.]])

In [ ]:
import numpy.linalg as la

#### linalg.inv(a)
Compute the inverse of a matrix.

In [ ]:
la.inv(np.random.rand(3,3))

array([[-28.80121412,  -8.66033528,  11.8874232 ],
       [ 12.0380633 ,   1.96208646,  -3.37913554],
       [  1.172346  ,   2.89879645,  -0.64212968]])

In [ ]:
a

array([[6., 1., 8., 9.],
       [2., 7., 2., 5.],
       [7., 6., 1., 9.],
       [1., 5., 5., 6.],
       [1., 4., 8., 5.]])

In [ ]:
a.sort(axis=0)

In [ ]:
a

array([[1., 1., 1., 5.],
       [1., 4., 2., 5.],
       [2., 5., 5., 6.],
       [6., 6., 8., 9.],
       [7., 7., 8., 9.]])

In [ ]:
a.sort(axis=1)
a

array([[1., 1., 1., 5.],
       [1., 2., 4., 5.],
       [2., 5., 5., 6.],
       [6., 6., 8., 9.],
       [7., 7., 8., 9.]])

In [ ]:
a = np.arange(100)

In [ ]:
b = a[[3,5,6]]

In [ ]:
b

array([3, 5, 6])

In [ ]:
b[0] = -4

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
b

array([-4,  5,  6])

In [ ]:
b = a[a<40]

In [ ]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
b = a[(a<40) & (a>30)]
b

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

### & | ~   : these are used for arrays

### And Or Not: these are used for single objects

In [ ]:
a = np.round(10*np.random.rand(2,3))
a

array([[ 2.,  6.,  8.],
       [ 7., 10.,  9.]])

In [ ]:
a+3

array([[ 5.,  9., 11.],
       [10., 13., 12.]])

In [ ]:
a+(np.arange(2).reshape(2,1))

array([[ 2.,  6.,  8.],
       [ 8., 11., 10.]])

In [ ]:
b = np.round(10*np.random.rand(2,2))

In [ ]:
a


array([[ 2.,  6.,  8.],
       [ 7., 10.,  9.]])

In [ ]:
b


array([[7., 4.],
       [6., 2.]])

In [ ]:
c = np.hstack((a,b))

In [ ]:
c

array([[ 2.,  6.,  8.,  7.,  4.],
       [ 7., 10.,  9.,  6.,  2.]])

In [ ]:
a = np.random.permutation(np.arange(10))

In [ ]:
a

array([5, 0, 9, 8, 6, 7, 4, 2, 1, 3])

In [ ]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.sort()
a = a[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
a = np.array(["abc","test","how are you","17a8h"])

In [ ]:
a.sort()
a

array(['17a8h', 'abc', 'how are you', 'test'], dtype='<U11')

In [ ]:
b = np.random.rand(1000000)

In [ ]:
%timeit sum(b)
%timeit np.sum(b)

77.8 ms ± 7.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
334 μs ± 10.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s

In [ ]:
%timeit mySum(b)


105 ms ± 10.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## ------   New Learning Resource ------

In [ ]:
import numpy as np

### Create a NumPy ndarray Object:

>NumPy is used to work with arrays. The array object in NumPy is called ndarray.


>We can create a NumPy ndarray object by using the array() function.

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

# type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


 `To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:`

In [ ]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Dimensions in Arrays
>A dimension in arrays is one level of array depth (nested arrays).


**nested array: are arrays that have arrays as their elements.**

### 0-D Arrays
>0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
arr = np.array(42)
print(arr)

42


### 1-D Arrays
>An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

>These are the most common and basic arrays.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D Arrays
>An array that has 1-D arrays as its elements is called a 2-D array.

>These are often used to represent matrix or 2nd order tensors.

**NumPy has a whole sub module dedicated towards matrix operations called numpy.mat**

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays
>An array that has 2-D arrays (matrices) as its elements is called 3-D array.

>These are often used to represent a 3rd order tensor.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions?
>NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

>An array can have any number of dimensions.

>When the array is created, you can define the number of dimensions by using the ndmin argument.

In [ ]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


`In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.`







# NumPy Array Indexing

### Access Array Elements
>Array indexing is the same as accessing an array element.

>You can access an array element by referring to its index number.

>The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
arr = np.array([1,2,3,4])
print(arr[0])

1


### Access 2-D Arrays
>To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

>Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1])
print('2nd element on 1st row: ', arr[0][1])

2nd element on 1st row:  2
2nd element on 1st row:  2


In [ ]:
arr[1,4]

np.int64(10)

### Access 3-D Arrays
>To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr[0][1][2])

6
6


### Negative Indexing
>Use negative indexing to access an array from the end.

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])
print('Last element from 2nd dim: ', arr[1][-1])

Last element from 2nd dim:  10
Last element from 2nd dim:  10


# NumPy Array Slicing

## Slicing arrays
>Slicing in python means taking elements from one given index to another given index.

>We pass slice instead of index like this: [start:end].

>We can also define the step, like this: [start:end:step].

>If we don't pass start its considered 0

>If we don't pass end its considered length of array in that dimension

>If we don't pass step its considered 1

In [ ]:
# Slice elements from index 1 to index 5 from the following array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5]

array([2, 3, 4, 5])

**Note: The result includes the start index, but excludes the end index.**

In [ ]:
# Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[4:]

array([5, 6, 7])

In [ ]:
# Slice elements from the beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[:4]

array([1, 2, 3, 4])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[:]

array([1, 2, 3, 4, 5, 6, 7])

###Negative Slicing
>Use the minus operator to refer to an index from the end:



In [ ]:
# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[-3:-1]

array([5, 6])

### STEP
>Use the step value to determine the step of the slicing:

In [ ]:
# Return every other element from index 1 to index 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5:2]

array([2, 4])

In [ ]:
# Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


## Slicing 2-D Arrays

In [ ]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
arr[1,1:4]
arr[::2][1:3]

array([[11, 12, 13, 14, 15]])

**Note: Remember that second element has index 1.**

In [ ]:
# From both elements, return index 2:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

---
## Data Types in Python

By default Python have these data types:

 * strings - used to represent text data, the text is given under quote marks.
e.g. "ABCD"

 * integer - used to represent integer numbers. e.g. -1, -2, -3

 * float - used to represent real numbers. e.g. 1.2, 42.42
  
 * boolean - used to represent True or False.
   
 * complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


---
## Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

 *   i - integer
 *   b - boolean
 *   u - unsigned integer
 *  f - float
 *   c - complex float
 *   m - timedelta
 *   M - datetime
 *   O - object
 *   S - string
 *   U - unicode string
*  V - fixed chunk of memory for other type ( void )
---

### Checking the Data Type of an Array

>The NumPy array object has a property called dtype that returns the data type of the array:

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


### Get the data type of an array containing strings:



In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


## Creating Arrays With a Defined Data Type

>We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

```Create an array with data type string:```


In [ ]:
import numpy as np
ar = np.array([1, 2, 3, 4], dtype='S')

print(ar)
print(ar.dtype)

[b'1' b'2' b'3' b'4']
|S1


```For i, u, f, S and U we can define size as well.```

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# What if a Value Can Not Be Converted?

> If a type is given in which elements can't be casted then NumPy will raise a ValueError.

**ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.**


A non integer string like 'a' can not be converted to integer (will raise an error):

In [ ]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

##Converting Data Type on Existing Arrays

>The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

>The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

>The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

Change data type from float to integer by using 'i' as parameter value:

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Change data type from float to integer by using int as parameter value:

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


Change data type from integer to boolean:

In [ ]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# NumPy Array Copy vs View

## The Difference Between Copy and View

> The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

> The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

> The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## COPY:

Make a copy, change the original array, and display both arrays:

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


**The copy SHOULD NOT be affected by the changes made to the original array.**

## VIEW:


Make a view, change the original array, and display both arrays:

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


**The view SHOULD be affected by the changes made to the original array.**

## Make Changes in the VIEW:
Make a view, change the view, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


**The original array SHOULD be affected by the changes made to the view.**

## Check if Array Owns its Data

>As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

>Every NumPy array has the attribute base that returns None if the array owns the data.

>Otherwise, the base  attribute refers to the original object.



Print the value of the base attribute to check if an array owns it's data or not:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


**The copy returns None.** <br/>
**The view returns the original array.**

---
# **NumPy Array Shape**

## Shape of an Array
> The shape of an array is the number of elements in each dimension.



## Get the Shape of an Array
> NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

Print the shape of a 2-D array:


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


```The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.```

In [ ]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
arr.shape

[[[[[1 2 3 4]]]]]


(1, 1, 1, 1, 4)

## What does the shape tuple represent?

>Integers at every index tells about the number of elements the corresponding dimension has.

>In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.


---
#**NumPy Array Reshaping**


## Reshaping arrays

>Reshaping means changing the shape of an array.

>The shape of an array is the number of elements in each dimension.

>By reshaping we can add or remove dimensions or change number of elements in each dimension.

## Reshape From 1-D to 2-D

Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Reshape From 1-D to 3-D


Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Can We Reshape Into any Shape?

>Yes, as long as the elements required for reshaping are equal in both shapes.

>We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [ ]:
# Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

# Returns Copy or View?

Check if the returned array is a copy or a view:

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


**The example above returns the original array, so it is a view.**

---
#Unknown Dimension

>You are allowed to have one "unknown" dimension.

>Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

>Pass -1 as the value, and NumPy will calculate this number for you.

Convert 1D array with 8 elements to 3D array with 2x2 elements:

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Note: We can not pass -1 to more than one dimension.**

# Flattening the arrays

>Flattening array means converting a multidimensional array into a 1D array.

>We can use reshape(-1) to do this.

In [17]:
# Convert the array into a 1D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


**Note: There are a lot of functions for changing the shapes of arrays in numpy ```flatten```, ```ravel``` and also for rearranging the elements ```rot90```, ```flip```, ```fliplr```, ```flipud``` etc. These fall under Intermediate to Advanced section of numpy.**

---
# **NumPy Array Iterating**

## Iterating Arrays

>Iterating means going through elements one by one.

>As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

>If we iterate on a 1-D array it will go through each element one by one.

In [19]:
# Iterate on the elements of the following 1-D array:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


## Iterating 2-D Arrays

In a 2-D array it will go through all the rows.

In [20]:
# Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


**If we iterate on a n-D array it will go through n-1th dimension one by one.**

To return the actual values, the scalars, we have to iterate the arrays in each dimension.

In [21]:
# Iterate on each scalar element of the 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


## Iterating 3-D Arrays
In a 3-D array it will go through all the 2-D arrays.

In [22]:
# Iterate on the elements of the following 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
