# NumPy

### numpy list is much faster that python list

In [5]:
import numpy as np

a = np.array([1,2,3,4,5],dtype='i')
b = np.array((1,6,3,4,9),dtype='f')
print(a)
print(b)

[1 2 3 4 5]
[1. 6. 3. 4. 9.]


In [5]:
type(a)
type(b)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float32')

----------------------------------------
### Demensions 

In [14]:
c = np.array([[1,2,3] , [4,5,6]])
print(c.ndim)

2


In [16]:
d = np.array([[[1,2,3] ,[4,5,6]],[[1,2,3],[4,5,6]]])
print(d)
print(d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [20]:
print(d.shape[0] , d.shape[1] , d.shape[2])
print(d[1,0,2])

2 2 3
3


In [22]:
print(d[0][1][0])

4


In [24]:
print(d[0,1,0])

4


In [30]:
c= np.array([[1,2],[1,2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [51]:
c = np.array([[[1,2,3],[4,5,6],[0,0,-1]], [[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

In [34]:
c.ndim

3

In [36]:
type(c)

numpy.ndarray

----------------------------------------
### shape  

#### $*$ The shape of an array is the number of elements in each dimension.

In [38]:
help(np.shape)

Help on _ArrayFunctionDispatcher in module numpy:

shape(a)
    Return the shape of an array.

    Parameters
    ----------
    a : array_like
        Input array.

    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.

    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.

    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()

    >>> a = np.array([(1, 2), (3, 4), (5, 6)],
    ...              dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (3,)
    >>> a.shape
    (3,)



In [40]:
c.shape

(2, 3, 3)

In [44]:
c.shape[1]

3

In [46]:
c.ndim

3

In [61]:
e = np.array([[[[1,2,3],[1,2,3]]]])
print(e.shape)
print(e.ndim)

(1, 1, 2, 3)
4


In [63]:
f = np.array([2])
f.ndim

1

In [65]:
g = np.array(3)

In [67]:
g.ndim

0

----------------------------------------
### size 

#### $*$ Gives the total number of elements .

In [77]:
print(g.size)
print(f.size)
print(e.size)
print(d.size)
print(c.size)
print(b.size)
print(a.size)

1
1
6
12
18
5
5


----------------------------------------
### nbytes



#### $*$The number of bytes that it takes in memory

In [75]:
print(g.nbytes)
print(f.nbytes)
print(e.nbytes)
print(d.nbytes)
print(c.nbytes)
print(b.nbytes)
print(a.nbytes)

4
4
24
48
72
20
20


### arange

#### arange(start, stop, step,, dtype) : Returns an array with evenly spaced elements as per the interval. 

In [7]:
a = np.arange(100)

In [11]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [15]:
a = np.arange(20,100,4,'float32')

In [17]:
print(a)

[20. 24. 28. 32. 36. 40. 44. 48. 52. 56. 60. 64. 68. 72. 76. 80. 84. 88.
 92. 96.]


### random

In [5]:
from numpy import random
x = random.randint(100)
print(x) 

91


In [48]:
x = random.randint(100, size=(5))
print(x)

[66 92 75 45 44]


In [50]:
x = random.randint(100, size=(3, 5))
print(x)

[[12 99 70 48  4]
 [53 64 22 24 50]
 [30 62 36 46 11]]


In [74]:
x = random.rand(10)
print(x)

[0.54978589 0.30809422 0.90717483 0.43686087 0.04850644 0.13160317
 0.64484335 0.28514687 0.53248315 0.50859871]


In [52]:
x = random.rand(3, 5)
print(x)

[[0.60545603 0.13934186 0.48933363 0.7203497  0.1732698 ]
 [0.67059157 0.43349478 0.46797112 0.82435309 0.2523013 ]
 [0.29625651 0.21425571 0.9607617  0.30893662 0.82758895]]


In [56]:
x = random.choice([3, 5, 7, 9])
print(x)

3


In [58]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[7 5 3 7 5]
 [7 7 9 5 9]
 [7 7 7 7 5]]


In [80]:
B = random.randn(10)
print(B)

[-0.97888345 -0.79536492 -0.67426448  0.81977847  0.51197223 -1.02094928
 -0.06235829 -0.41682735 -1.01111964  1.05155149]


In [82]:
C  = random.rand(2,3,4,2)
print(C)

[[[[0.69991983 0.44297422]
   [0.68137032 0.16075331]
   [0.81763751 0.4353439 ]
   [0.30843444 0.63491917]]

  [[0.98236918 0.97956565]
   [0.38781851 0.41128512]
   [0.98800561 0.5685431 ]
   [0.0256113  0.19179184]]

  [[0.37856993 0.09644467]
   [0.93561366 0.87012338]
   [0.03263357 0.74651193]
   [0.57748844 0.35463929]]]


 [[[0.24477976 0.10164465]
   [0.05064284 0.10545007]
   [0.52069016 0.23627739]
   [0.54072417 0.62901753]]

  [[0.79742042 0.59390395]
   [0.93077873 0.39404464]
   [0.35461336 0.1367498 ]
   [0.15993369 0.15032652]]

  [[0.07328601 0.08239671]
   [0.19595304 0.89916789]
   [0.7286973  0.62283415]
   [0.37536003 0.33834137]]]]


### Permutations 

#### A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa. 

In [84]:
A = random.permutation(np.arange(10))
print(A)

[8 5 0 6 7 2 3 1 9 4]


###  reshape


#### Reshaping means changing the shape of an array.

#### The shape of an array is the number of elements in each dimension.


#### By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [86]:
D = np.arange(100).reshape(4, 25)
print(D)
print(D.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]
(4, 25)


In [88]:
D = np.arange(100).reshape(4, 5,5)
print(D)
print(D.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]
(4, 5, 5)


### Slicing

In [9]:
import numpy as np
a = np.arange(100)
b = a[3:10]

In [12]:
b

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
b[0] = -1200
b

array([-1200,     4,     5,     6,     7,     8,     9])

In [16]:
a

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [20]:
b = a[5:21].copy()
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
a[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [24]:
a[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [26]:
a ==-1200

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [32]:
b = (a==-1200)*np.arange(a.size)
b

array([0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
idx = np.argwhere(a==-1200)[0][0]

In [40]:
idx

3

In [42]:
a[idx] = 3
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
a = np.round(10*np.random.rand(5,4))
a

array([[6., 1., 8., 9.],
       [2., 7., 2., 5.],
       [7., 6., 1., 9.],
       [1., 5., 5., 6.],
       [1., 4., 8., 5.]])

In [46]:
a[1,2]

7.0

In [48]:
a[1,:]

array([ 8.,  8.,  7., 10.])

In [50]:
a[:,2]

array([9., 7., 5., 9., 5.])

In [54]:
a[1:3,2:4]

array([[ 7., 10.],
       [ 5.,  0.]])

#### The transpose of a matrix is obtained by moving the rows data to the column and columns data to the rows .

In [56]:
a.T

array([[ 4.,  8.,  9.,  9.,  1.],
       [ 5.,  8.,  5.,  1.,  4.],
       [ 9.,  7.,  5.,  9.,  5.],
       [ 5., 10.,  0.,  5.,  9.]])

In [66]:
import numpy.linalg as la

#### linalg.inv(a)
Compute the inverse of a matrix.

In [68]:
la.inv(np.random.rand(3,3))

array([[-28.80121412,  -8.66033528,  11.8874232 ],
       [ 12.0380633 ,   1.96208646,  -3.37913554],
       [  1.172346  ,   2.89879645,  -0.64212968]])

In [23]:
a

array([[6., 1., 8., 9.],
       [2., 7., 2., 5.],
       [7., 6., 1., 9.],
       [1., 5., 5., 6.],
       [1., 4., 8., 5.]])

In [25]:
a.sort(axis=0)

In [27]:
a

array([[1., 1., 1., 5.],
       [1., 4., 2., 5.],
       [2., 5., 5., 6.],
       [6., 6., 8., 9.],
       [7., 7., 8., 9.]])

In [29]:
a.sort(axis=1)
a

array([[1., 1., 1., 5.],
       [1., 2., 4., 5.],
       [2., 5., 5., 6.],
       [6., 6., 8., 9.],
       [7., 7., 8., 9.]])

In [31]:
a = np.arange(100)

In [33]:
b = a[[3,5,6]]

In [35]:
b

array([3, 5, 6])

In [37]:
b[0] = -4

In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [41]:
b

array([-4,  5,  6])

In [43]:
b = a[a<40]

In [45]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [51]:
b = a[(a<40) & (a>30)]
b

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

### & | ~   : these are used for arrays 

### And Or Not: these are used for single objects

In [55]:
a = np.round(10*np.random.rand(2,3))
a

array([[ 2.,  6.,  8.],
       [ 7., 10.,  9.]])

In [57]:
a+3

array([[ 5.,  9., 11.],
       [10., 13., 12.]])

In [59]:
a+(np.arange(2).reshape(2,1))

array([[ 2.,  6.,  8.],
       [ 8., 11., 10.]])

In [61]:
b = np.round(10*np.random.rand(2,2))

In [67]:
a


array([[ 2.,  6.,  8.],
       [ 7., 10.,  9.]])

In [69]:
b


array([[7., 4.],
       [6., 2.]])

In [75]:
c = np.hstack((a,b))

In [77]:
c

array([[ 2.,  6.,  8.,  7.,  4.],
       [ 7., 10.,  9.,  6.,  2.]])

In [79]:
a = np.random.permutation(np.arange(10))

In [81]:
a

array([5, 0, 9, 8, 6, 7, 4, 2, 1, 3])

In [83]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a.sort()
a = a[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [89]:
a = np.array(["abc","test","how are you","17a8h"])

In [97]:
a.sort()
a

array(['17a8h', 'abc', 'how are you', 'test'], dtype='<U11')

In [99]:
b = np.random.rand(1000000)

In [101]:
%timeit sum(b)
%timeit np.sum(b)

77.8 ms ± 7.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
334 μs ± 10.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [103]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s    

In [105]:
%timeit mySum(b)


105 ms ± 10.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
