# NumPy

### numpy list is much faster that python list

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5],dtype='i')
b = np.array((1,6,3,4,9),dtype='f')
print(a)
print(b)

[1 2 3 4 5]
[1. 6. 3. 4. 9.]


In [ ]:
type(a)
type(b)

numpy.ndarray

In [ ]:
a.dtype

dtype('int32')

In [ ]:
b.dtype

dtype('float32')

----------------------------------------
### Demensions

In [ ]:
c = np.array([[1,2,3] , [4,5,6]])
print(c.ndim)

2


In [ ]:
d = np.array([[[1,2,3] ,[4,5,6]],[[1,2,3],[4,5,6]]])
print(d)
print(d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
print(d.shape[0] , d.shape[1] , d.shape[2])
print(d[1,0,2])

2 2 3
3


In [ ]:
print(d[0][1][0])

4


In [ ]:
print(d[0,1,0])

4


In [ ]:
c= np.array([[1,2],[1,2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
c = np.array([[[1,2,3],[4,5,6],[0,0,-1]], [[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

In [ ]:
c.ndim

3

In [ ]:
type(c)

numpy.ndarray

----------------------------------------
### shape  

#### $*$ The shape of an array is the number of elements in each dimension.

In [ ]:
help(np.shape)

Help on _ArrayFunctionDispatcher in module numpy:

shape(a)
    Return the shape of an array.

    Parameters
    ----------
    a : array_like
        Input array.

    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.

    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.

    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()

    >>> a = np.array([(1, 2), (3, 4), (5, 6)],
    ...              dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (3,)
    >>> a.shape
    (3,)



In [ ]:
c.shape

(2, 3, 3)

In [ ]:
c.shape[1]

3

In [ ]:
c.ndim

3

In [ ]:
e = np.array([[[[1,2,3],[1,2,3]]]])
print(e.shape)
print(e.ndim)

(1, 1, 2, 3)
4


In [ ]:
f = np.array([2])
f.ndim

1

In [ ]:
g = np.array(3)

In [ ]:
g.ndim

0

----------------------------------------
### size

#### $*$ Gives the total number of elements .

In [ ]:
print(g.size)
print(f.size)
print(e.size)
print(d.size)
print(c.size)
print(b.size)
print(a.size)

1
1
6
12
18
5
5


----------------------------------------
### nbytes



#### $*$The number of bytes that it takes in memory

In [ ]:
print(g.nbytes)
print(f.nbytes)
print(e.nbytes)
print(d.nbytes)
print(c.nbytes)
print(b.nbytes)
print(a.nbytes)

4
4
24
48
72
20
20


### arange

#### arange(start, stop, step,, dtype) : Returns an array with evenly spaced elements as per the interval.

In [ ]:
a = np.arange(100)

In [ ]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
a = np.arange(20,100,4,'float32')

In [ ]:
print(a)

[20. 24. 28. 32. 36. 40. 44. 48. 52. 56. 60. 64. 68. 72. 76. 80. 84. 88.
 92. 96.]


### random

In [ ]:
from numpy import random
x = random.randint(100)
print(x)

91


In [ ]:
x = random.randint(100, size=(5))
print(x)

[66 92 75 45 44]


In [ ]:
x = random.randint(100, size=(3, 5))
print(x)

[[12 99 70 48  4]
 [53 64 22 24 50]
 [30 62 36 46 11]]


In [ ]:
x = random.rand(10)
print(x)

[0.54978589 0.30809422 0.90717483 0.43686087 0.04850644 0.13160317
 0.64484335 0.28514687 0.53248315 0.50859871]


In [ ]:
x = random.rand(3, 5)
print(x)

[[0.60545603 0.13934186 0.48933363 0.7203497  0.1732698 ]
 [0.67059157 0.43349478 0.46797112 0.82435309 0.2523013 ]
 [0.29625651 0.21425571 0.9607617  0.30893662 0.82758895]]


In [ ]:
x = random.choice([3, 5, 7, 9])
print(x)

3


In [ ]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[7 5 3 7 5]
 [7 7 9 5 9]
 [7 7 7 7 5]]


In [ ]:
B = random.randn(10)
print(B)

[-0.97888345 -0.79536492 -0.67426448  0.81977847  0.51197223 -1.02094928
 -0.06235829 -0.41682735 -1.01111964  1.05155149]


In [ ]:
C  = random.rand(2,3,4,2)
print(C)

[[[[0.69991983 0.44297422]
   [0.68137032 0.16075331]
   [0.81763751 0.4353439 ]
   [0.30843444 0.63491917]]

  [[0.98236918 0.97956565]
   [0.38781851 0.41128512]
   [0.98800561 0.5685431 ]
   [0.0256113  0.19179184]]

  [[0.37856993 0.09644467]
   [0.93561366 0.87012338]
   [0.03263357 0.74651193]
   [0.57748844 0.35463929]]]


 [[[0.24477976 0.10164465]
   [0.05064284 0.10545007]
   [0.52069016 0.23627739]
   [0.54072417 0.62901753]]

  [[0.79742042 0.59390395]
   [0.93077873 0.39404464]
   [0.35461336 0.1367498 ]
   [0.15993369 0.15032652]]

  [[0.07328601 0.08239671]
   [0.19595304 0.89916789]
   [0.7286973  0.62283415]
   [0.37536003 0.33834137]]]]


### Permutations

#### A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

In [ ]:
A = random.permutation(np.arange(10))
print(A)

[8 5 0 6 7 2 3 1 9 4]


###  reshape


#### Reshaping means changing the shape of an array.

#### The shape of an array is the number of elements in each dimension.


#### By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
D = np.arange(100).reshape(4, 25)
print(D)
print(D.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]
(4, 25)


In [ ]:
D = np.arange(100).reshape(4, 5,5)
print(D)
print(D.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]
(4, 5, 5)


### Slicing

In [ ]:
import numpy as np
a = np.arange(100)
b = a[3:10]

In [ ]:
b

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
b[0] = -1200
b

array([-1200,     4,     5,     6,     7,     8,     9])

In [ ]:
a

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [ ]:
b = a[5:21].copy()
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
a[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
a[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [ ]:
a ==-1200

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
b = (a==-1200)*np.arange(a.size)
b

array([0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
idx = np.argwhere(a==-1200)[0][0]

In [ ]:
idx

3

In [ ]:
a[idx] = 3
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a = np.round(10*np.random.rand(5,4))
a

array([[6., 1., 8., 9.],
       [2., 7., 2., 5.],
       [7., 6., 1., 9.],
       [1., 5., 5., 6.],
       [1., 4., 8., 5.]])

In [ ]:
a[1,2]

7.0

In [ ]:
a[1,:]

array([ 8.,  8.,  7., 10.])

In [ ]:
a[:,2]

array([9., 7., 5., 9., 5.])

In [ ]:
a[1:3,2:4]

array([[ 7., 10.],
       [ 5.,  0.]])

#### The transpose of a matrix is obtained by moving the rows data to the column and columns data to the rows .

In [ ]:
a.T

array([[ 4.,  8.,  9.,  9.,  1.],
       [ 5.,  8.,  5.,  1.,  4.],
       [ 9.,  7.,  5.,  9.,  5.],
       [ 5., 10.,  0.,  5.,  9.]])

In [ ]:
import numpy.linalg as la

#### linalg.inv(a)
Compute the inverse of a matrix.

In [ ]:
la.inv(np.random.rand(3,3))

array([[-28.80121412,  -8.66033528,  11.8874232 ],
       [ 12.0380633 ,   1.96208646,  -3.37913554],
       [  1.172346  ,   2.89879645,  -0.64212968]])

In [ ]:
a

array([[6., 1., 8., 9.],
       [2., 7., 2., 5.],
       [7., 6., 1., 9.],
       [1., 5., 5., 6.],
       [1., 4., 8., 5.]])

In [ ]:
a.sort(axis=0)

In [ ]:
a

array([[1., 1., 1., 5.],
       [1., 4., 2., 5.],
       [2., 5., 5., 6.],
       [6., 6., 8., 9.],
       [7., 7., 8., 9.]])

In [ ]:
a.sort(axis=1)
a

array([[1., 1., 1., 5.],
       [1., 2., 4., 5.],
       [2., 5., 5., 6.],
       [6., 6., 8., 9.],
       [7., 7., 8., 9.]])

In [ ]:
a = np.arange(100)

In [ ]:
b = a[[3,5,6]]

In [ ]:
b

array([3, 5, 6])

In [ ]:
b[0] = -4

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
b

array([-4,  5,  6])

In [ ]:
b = a[a<40]

In [ ]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
b = a[(a<40) & (a>30)]
b

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

### & | ~   : these are used for arrays

### And Or Not: these are used for single objects

In [ ]:
a = np.round(10*np.random.rand(2,3))
a

array([[ 2.,  6.,  8.],
       [ 7., 10.,  9.]])

In [ ]:
a+3

array([[ 5.,  9., 11.],
       [10., 13., 12.]])

In [ ]:
a+(np.arange(2).reshape(2,1))

array([[ 2.,  6.,  8.],
       [ 8., 11., 10.]])

In [ ]:
b = np.round(10*np.random.rand(2,2))

In [ ]:
a


array([[ 2.,  6.,  8.],
       [ 7., 10.,  9.]])

In [ ]:
b


array([[7., 4.],
       [6., 2.]])

In [ ]:
c = np.hstack((a,b))

In [ ]:
c

array([[ 2.,  6.,  8.,  7.,  4.],
       [ 7., 10.,  9.,  6.,  2.]])

In [ ]:
a = np.random.permutation(np.arange(10))

In [ ]:
a

array([5, 0, 9, 8, 6, 7, 4, 2, 1, 3])

In [ ]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.sort()
a = a[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
a = np.array(["abc","test","how are you","17a8h"])

In [ ]:
a.sort()
a

array(['17a8h', 'abc', 'how are you', 'test'], dtype='<U11')

In [ ]:
b = np.random.rand(1000000)

In [ ]:
%timeit sum(b)
%timeit np.sum(b)

77.8 ms ± 7.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
334 μs ± 10.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s

In [ ]:
%timeit mySum(b)


105 ms ± 10.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## ------   New Learning Resource ------

In [ ]:
import numpy as np

### Create a NumPy ndarray Object:

>NumPy is used to work with arrays. The array object in NumPy is called ndarray.


>We can create a NumPy ndarray object by using the array() function.

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

# type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


 `To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:`

In [ ]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Dimensions in Arrays
>A dimension in arrays is one level of array depth (nested arrays).


**nested array: are arrays that have arrays as their elements.**

### 0-D Arrays
>0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
arr = np.array(42)
print(arr)

42


### 1-D Arrays
>An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

>These are the most common and basic arrays.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D Arrays
>An array that has 1-D arrays as its elements is called a 2-D array.

>These are often used to represent matrix or 2nd order tensors.

**NumPy has a whole sub module dedicated towards matrix operations called numpy.mat**

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays
>An array that has 2-D arrays (matrices) as its elements is called 3-D array.

>These are often used to represent a 3rd order tensor.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions?
>NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

>An array can have any number of dimensions.

>When the array is created, you can define the number of dimensions by using the ndmin argument.

In [ ]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


`In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.`







# NumPy Array Indexing

### Access Array Elements
>Array indexing is the same as accessing an array element.

>You can access an array element by referring to its index number.

>The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
arr = np.array([1,2,3,4])
print(arr[0])

1


### Access 2-D Arrays
>To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

>Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1])
print('2nd element on 1st row: ', arr[0][1])

2nd element on 1st row:  2
2nd element on 1st row:  2


In [ ]:
arr[1,4]

np.int64(10)

### Access 3-D Arrays
>To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr[0][1][2])

6
6


### Negative Indexing
>Use negative indexing to access an array from the end.

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])
print('Last element from 2nd dim: ', arr[1][-1])

Last element from 2nd dim:  10
Last element from 2nd dim:  10


# NumPy Array Slicing

## Slicing arrays
>Slicing in python means taking elements from one given index to another given index.

>We pass slice instead of index like this: [start:end].

>We can also define the step, like this: [start:end:step].

>If we don't pass start its considered 0

>If we don't pass end its considered length of array in that dimension

>If we don't pass step its considered 1

In [ ]:
# Slice elements from index 1 to index 5 from the following array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5]

array([2, 3, 4, 5])

**Note: The result includes the start index, but excludes the end index.**

In [ ]:
# Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[4:]

array([5, 6, 7])

In [ ]:
# Slice elements from the beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[:4]

array([1, 2, 3, 4])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[:]

array([1, 2, 3, 4, 5, 6, 7])

###Negative Slicing
>Use the minus operator to refer to an index from the end:



In [ ]:
# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[-3:-1]

array([5, 6])

### STEP
>Use the step value to determine the step of the slicing:

In [ ]:
# Return every other element from index 1 to index 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5:2]

array([2, 4])

In [ ]:
# Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


## Slicing 2-D Arrays

In [ ]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
arr[1,1:4]
arr[::2][1:3]

array([[11, 12, 13, 14, 15]])

**Note: Remember that second element has index 1.**

In [ ]:
# From both elements, return index 2:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

---
## Data Types in Python

By default Python have these data types:

 * strings - used to represent text data, the text is given under quote marks.
e.g. "ABCD"

 * integer - used to represent integer numbers. e.g. -1, -2, -3

 * float - used to represent real numbers. e.g. 1.2, 42.42
  
 * boolean - used to represent True or False.
   
 * complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


---
## Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

 *   i - integer
 *   b - boolean
 *   u - unsigned integer
 *  f - float
 *   c - complex float
 *   m - timedelta
 *   M - datetime
 *   O - object
 *   S - string
 *   U - unicode string
*  V - fixed chunk of memory for other type ( void )
---

### Checking the Data Type of an Array

>The NumPy array object has a property called dtype that returns the data type of the array:

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


### Get the data type of an array containing strings:



In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


## Creating Arrays With a Defined Data Type

>We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

```Create an array with data type string:```


In [ ]:
import numpy as np
ar = np.array([1, 2, 3, 4], dtype='S')

print(ar)
print(ar.dtype)

[b'1' b'2' b'3' b'4']
|S1


```For i, u, f, S and U we can define size as well.```

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# What if a Value Can Not Be Converted?

> If a type is given in which elements can't be casted then NumPy will raise a ValueError.

**ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.**


A non integer string like 'a' can not be converted to integer (will raise an error):

In [ ]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

##Converting Data Type on Existing Arrays

>The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

>The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

>The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

Change data type from float to integer by using 'i' as parameter value:

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Change data type from float to integer by using int as parameter value:

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


Change data type from integer to boolean:

In [ ]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# NumPy Array Copy vs View

## The Difference Between Copy and View

> The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

> The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

> The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## COPY:

Make a copy, change the original array, and display both arrays:

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


**The copy SHOULD NOT be affected by the changes made to the original array.**

## VIEW:


Make a view, change the original array, and display both arrays:

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


**The view SHOULD be affected by the changes made to the original array.**

## Make Changes in the VIEW:
Make a view, change the view, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


**The original array SHOULD be affected by the changes made to the view.**

## Check if Array Owns its Data

>As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

>Every NumPy array has the attribute base that returns None if the array owns the data.

>Otherwise, the base  attribute refers to the original object.



Print the value of the base attribute to check if an array owns it's data or not:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


**The copy returns None.** <br/>
**The view returns the original array.**

---
# **NumPy Array Shape**

## Shape of an Array
> The shape of an array is the number of elements in each dimension.



## Get the Shape of an Array
> NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

Print the shape of a 2-D array:


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


```The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.```

In [ ]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
arr.shape

[[[[[1 2 3 4]]]]]


(1, 1, 1, 1, 4)

## What does the shape tuple represent?

>Integers at every index tells about the number of elements the corresponding dimension has.

>In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.


---
#**NumPy Array Reshaping**


## Reshaping arrays

>Reshaping means changing the shape of an array.

>The shape of an array is the number of elements in each dimension.

>By reshaping we can add or remove dimensions or change number of elements in each dimension.

## Reshape From 1-D to 2-D

Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Reshape From 1-D to 3-D


Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Can We Reshape Into any Shape?

>Yes, as long as the elements required for reshaping are equal in both shapes.

>We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [ ]:
# Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

# Returns Copy or View?

Check if the returned array is a copy or a view:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


**The example above returns the original array, so it is a view.**

---
#Unknown Dimension

>You are allowed to have one "unknown" dimension.

>Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

>Pass -1 as the value, and NumPy will calculate this number for you.

Convert 1D array with 8 elements to 3D array with 2x2 elements:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Note: We can not pass -1 to more than one dimension.**

# Flattening the arrays

>Flattening array means converting a multidimensional array into a 1D array.

>We can use reshape(-1) to do this.

In [ ]:
# Convert the array into a 1D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


**Note: There are a lot of functions for changing the shapes of arrays in numpy ```flatten```, ```ravel``` and also for rearranging the elements ```rot90```, ```flip```, ```fliplr```, ```flipud``` etc. These fall under Intermediate to Advanced section of numpy.**

---
# **NumPy Array Iterating**

## Iterating Arrays

>Iterating means going through elements one by one.

>As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

>If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
# Iterate on the elements of the following 1-D array:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


## Iterating 2-D Arrays

In a 2-D array it will go through all the rows.

In [ ]:
# Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


**If we iterate on a n-D array it will go through n-1th dimension one by one.**

To return the actual values, the scalars, we have to iterate the arrays in each dimension.

In [ ]:
# Iterate on each scalar element of the 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


## Iterating 3-D Arrays
In a 3-D array it will go through all the 2-D arrays.

In [ ]:
# Iterate on the elements of the following 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


To return the actual values, the scalars, we have to iterate the arrays in each dimension.


In [ ]:
# Iterate down to the scalars:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# **Iterating Arrays Using nditer()**

>The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

## Iterating on Each Scalar Element

>In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [ ]:
# Iterate through the following 3-D array:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np


##Iterating Array With Different Data Types

>We can use **op_dtypes** argument and pass it the expected datatype to change the datatype of elements while iterating.

>NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in **nditer()** we pass **flags=['buffered']**.

In [ ]:
# Iterate through the array as a string:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


##Iterating With Different Step Size

>We can use filtering and followed by iteration.

In [ ]:
# Iterate through every scalar element of the 2D array skipping 1 element:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


## Enumerated Iteration Using ndenumerate()

>Enumeration means mentioning sequence number of somethings one by one.

>Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [ ]:
# Enumerate on following 1D arrays elements:

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
#Enumerate on following 2D array's elements:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


---
## **NumPy Joining Array**

>Joining NumPy Arrays:

>Joining means putting contents of two or more arrays in a single array.

>In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

>We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.


In [ ]:
# Join two arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


##Joining Arrays Using Stack Functions:

>Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

>We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

>We pass a sequence of arrays that we want to join to the **stack()** method along with the axis. If axis is not explicitly passed it is taken as 0.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


##Stacking Along Rows:

>NumPy provides a helper function: **hstack()** to stack along rows.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


##Stacking Along Columns

>NumPy provides a helper function: **vstack()**  to stack along columns.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


##Stacking Along Height (depth)

>NumPy provides a helper function: **dstack()** to stack along height, which is the same as depth.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]



---

### **1. `np.stack`**

* **General-purpose stacking along a new axis.**
* It joins a sequence of arrays **along a new dimension** (adds an axis).
* All input arrays must have the **same shape**.

```python
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.stack([a, b])       
# [[1 2 3]
#  [4 5 6]]

np.stack([a, b], axis=1)  
# [[1 4]
#  [2 5]
#  [3 6]]
```

👉 Adds a new axis, unlike `concatenate`.

---

### **2. `np.concatenate`**

* **Joins arrays along an existing axis.**
* Does **not create a new axis**.
* Arrays must have the same shape **except along the concatenation axis**.

```python
np.concatenate([a, b])      
# [1 2 3 4 5 6]   (along axis=0)

np.concatenate([a[np.newaxis, :], b[np.newaxis, :]], axis=0)
# [[1 2 3]
#  [4 5 6]]
```

---

### **3. `np.hstack`**  (Horizontal stack)

* Special case of `concatenate`:
* For **1D arrays**: just concatenates (same as `concatenate`).
* For **2D arrays**: stacks **column-wise** (along axis=1).
* Shortcut for `np.concatenate(..., axis=1)` (for 2D+).

```python
np.hstack([a, b])       
# [1 2 3 4 5 6]   (1D)

A = np.array([[1],[2],[3]])
B = np.array([[4],[5],[6]])
np.hstack([A, B])
# [[1 4]
#  [2 5]
#  [3 6]]
```

---

### **4. `np.vstack`**  (Vertical stack)

* Stacks **row-wise** (along axis=0).
* Shortcut for `np.concatenate(..., axis=0)` (after reshaping 1D inputs).

```python
np.vstack([a, b])
# [[1 2 3]
#  [4 5 6]]

np.vstack([A, B])
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]
#  [6]]
```

---

### **5. `np.dstack`**  (Depth stack)

* Stacks along the **third axis** (`axis=2`).
* Works like making a **“depth cube”**.

```python
np.dstack([a, b])
# [[[1 4]
#   [2 5]
#   [3 6]]]

C = np.array([[1,2],[3,4]])
D = np.array([[5,6],[7,8]])
np.dstack([C, D])
# [[[1 5]
#   [2 6]]
#  [[3 7]
#   [4 8]]]
```

---

### ✅ Quick Summary

| Function          | Axis behavior                | Adds new axis? | Example use case        |
| ----------------- | ---------------------------- | -------------- | ----------------------- |
| **`stack`**       | New axis (you choose `axis`) | ✅ Yes          | Build higher-dim arrays |
| **`concatenate`** | Existing axis                | ❌ No           | Simple joining          |
| **`hstack`**      | Horizontal (`axis=1` for 2D) | ❌ No           | Column-wise joining     |
| **`vstack`**      | Vertical (`axis=0`)          | ❌ No           | Row-wise joining        |
| **`dstack`**      | Depth (`axis=2`)             | ❌ No           | Add depth dimension     |

---




## **NumPy Splitting Array**

###Splitting NumPy Arrays:

>Splitting is reverse operation of Joining.

>Joining merges multiple arrays into one and Splitting breaks one array into multiple.

>We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
#Split the array in 3 parts:

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


**Note:** The return value is a list containing three arrays.

>If the array has less elements than required, it will adjust from the end accordingly.

In [ ]:
# Split the array in 4 parts:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


**Note:** We also have the method `split()` available but it will not adjust the elements when elements are less in source array for splitting like in example above, `array_split()` worked properly but `split()` would fail.

##Split Into Arrays:

>The return value of the `array_split()` method is a list containing each of the split as an array.

>If you split an array into 3 arrays, you can access them from the result just like any array element:

In [ ]:
# Access the splitted arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


##Splitting 2-D Arrays:

>Use the same syntax when splitting 2-D arrays.

>Use the `array_split()` method, pass in the array you want to split and the number of splits you want to do.

In [ ]:
# Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


>The example above returns three 2-D arrays.

>Let's look at another example, this time each element in the 2-D arrays contains 3 elements.

In [ ]:
# Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


>The example above returns three 2-D arrays.

>In addition, you can specify which axis you want to do the split around.

>The example below also returns three 2-D arrays, but they are split along the column (axis=1).

In [ ]:
# Split the 2-D array into three 2-D arrays along columns.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


>An alternate solution is using `hsplit()` opposite of `hstack()`

In [ ]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along columns.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]])
newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**Note:** Similar alternates to `vstack()` and `dstack()` are available as `vsplit()` and `dsplit()`.

---
## **NumPy Searching Arrays**
###Searching Arrays:

>You can search an array for a certain value, and return the indexes that get a match.

>To search an array, use the `where()` method.

In [ ]:
#Find the indexes where the value is 4:

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


>The example above will return a tuple: (array([3, 5, 6],)

>Which means that the value 4 is present at index 3, 5, and 6.

In [ ]:
# Find the indexes where the values are even:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
#Find the indexes where the values are odd:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


✈ ✈ ✈ ✈ ✈ ✈
## Search Sorted:

>There is a method called `searchsorted()` which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

**The `searchsorted()` method is assumed to be used on sorted arrays.**


In [ ]:
#Find the indexes where the value 7 should be inserted:

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)

print(x)

1


>Example explained: The number 7 should be inserted on index 1 to remain the sort order.

>The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

## Search From the Right Side:

>By default the left most index is returned, but we can give `side='right'` to return the right most index instead.

In [ ]:
# Find the indexes where the value 7 should be inserted, starting from the right:

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')

print(x)

2


>Example explained: The number 7 should be inserted on index 2 to remain the sort order.

>The method starts the search from the right and returns the first index where the number 7 is no longer less than the next value.

##Multiple Values:

>To search for more than one value, use an array with the specified values.

In [ ]:
#Find the indexes where the values 2, 4, and 6 should be inserted:

arr = np.array([1, 3, 5, 8])
x = np.searchsorted(arr, [2, 6, 7])

print(x)

[1 3 3]


>The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.

---
## **NumPy Sorting Arrays**

### Sorting Arrays:

>Sorting means putting elements in an ordered sequence.

>Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

>The NumPy ndarray object has a function called `sort()`, that will sort a specified array.

In [ ]:
# Sort the array:

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


**Note: This method returns a copy of the array, leaving the original array unchanged.**

>You can also sort arrays of strings, or any other data type:

In [ ]:
# Sort the array alphabetically:

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
#Sort a boolean array:

arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


## Sorting a 2-D Array

>If you use the `sort()` method on a 2-D array, both arrays will be sorted:

In [ ]:
# Sort a 2-D array:

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## **NumPy Filter Array**

### Filtering Arrays:

>Getting some elements out of an existing array and creating a new array out of them is called filtering.

>In NumPy, you filter an array using a boolean index list.

 ☣ **A boolean index list is a list of booleans corresponding to indexes in the array.**

>If the value at an index is `True` that element is contained in the filtered array, if the value at that index is `False` that element is excluded from the filtered array.

In [ ]:
# Create an array from the elements on index 0 and 2:

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]

print(newarr)

[41 43]


>The example above will return `[41, 43]`, why?

>Because the new array contains only the values where the filter array had the value `True`, in this case, index 0 and 2.

## Creating the Filter Array

>In the example above we hard-coded the `True` and `False` values, but the common use is to create a filter array based on conditions.

In [ ]:
# Create a filter array that will return only values higher than 42:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
# Create a filter array that will return only even elements from the original array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


## Creating Filter Directly From Array:

>The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

>We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [ ]:
# Create a filter array that will return only values higher than 42:

arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
# Create a filter array that will return only even elements from the original array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴✴

# **Random Numbers in NumPy**

###What is a Random Number?

>Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

## Pseudo Random and True Random.

>Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

>If there is a program to generate random number it can be predicted, thus it is not truly random.

>Random numbers generated through a generation algorithm are called pseudo random.

`Can we make truly random numbers?`

>Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

>We do not need truly random numbers, unless it is related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

*In this tutorial we will be using pseudo random numbers.*

##Generate Random Number:

> NumPy offers the random module to work with random numbers.

In [ ]:
# Generate a random integer from 0 to 100:
from numpy import random

x = random.randint(100)

print(x)

13


##Generate Random Float:

>The random module's `rand()` method returns a random float between 0 and 1.

In [ ]:
# Generate a random float from 0 to 1:

x = random.rand()
print(x)

0.32913331305141724


## Generate Random Array:

>In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.
Integers

>The `randint()` method takes a size parameter where you can specify the shape of an array.

In [ ]:
# Generate a 1-D array containing 5 random integers from 0 to 100:

x=random.randint(100, size=(5))
print(x)

[40  4 14 57 77]


In [ ]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

x = random.randint(100, size=(3, 5))
print(x)

[[ 8 13 82 20  5]
 [35 48 20 19 62]
 [27 11 47 74 54]]


##Floats:

>The `rand()` method also allows you to specify the shape of the array.

In [ ]:
# Generate a 1-D array containing 5 random floats:

x = random.rand(5)
print(x)

[0.79800931 0.42334007 0.58070037 0.7019545  0.18657248]


In [49]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.22813304 0.90069154 0.98248839 0.516075   0.99319039]
 [0.03536969 0.70510835 0.02936783 0.13850241 0.50405041]
 [0.54743387 0.25460575 0.19710907 0.35256393 0.81826365]]


## Generate Random Number From Array:

>The `choice()` method allows you to generate a random value based on an array of values.

>The `choice()` method takes an array as a parameter and randomly returns one of the values.

In [52]:
#Return one of the values in an array:

x = random.choice([3, 5, 7, 9])
print(x)

3


>The `choice()` method also allows you to return an array of values.

>Add a size parameter to specify the shape of the array.

In [53]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[3 5 3 5 7]
 [9 5 7 7 9]
 [7 3 3 9 3]]


#**Random Data Distribution**

##⁉ What is Data Distribution?

>Data Distribution is a list of all possible values, and how often each value occurs.

>Such lists are important when working with statistics and data science.

>The random module offer methods that returns randomly generated data distributions.


##Random Distribution:

>A random distribution is a set of random numbers that follow a certain probability density function.

>**Probability Density Function**: A function that describes a continuous probability. i.e. probability of all values in an array.


>We can generate random numbers based on defined probabilities using the `choice()` method of the `random` module.

>The `choice()` method allows us to specify the probability for each value.

>The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

In [59]:
#Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.
#The probability for the value to be 3 is set to be 0.1
#The probability for the value to be 5 is set to be 0.3
#The probability for the value to be 7 is set to be 0.6
#The probability for the value to be 9 is set to be 0

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)
print(x.size)

[3 7 5 7 7 7 5 7 7 5 7 5 5 3 5 3 7 7 7 5 5 7 3 7 5 5 7 7 3 5 7 5 7 7 7 5 7
 3 5 7 7 7 3 7 7 5 7 7 7 3 5 7 7 3 7 7 7 7 5 3 7 5 7 7 7 3 7 3 7 5 7 7 7 3
 7 7 5 7 3 7 7 7 5 7 7 5 7 7 5 7 5 7 5 5 5 7 7 7 7 7]
100



**The sum of all probability numbers should be 1.**

>Even if you run the example above 100 times, the value 9 will never occur.

>You can return arrays of any shape and size by specifying the shape in the size parameter.

In [60]:
# Same example as above, but return a 2-D array with 3 rows, each containing 5 values.

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[7 7 5 5 7]
 [7 7 3 5 7]
 [7 7 5 5 5]]
